// Central site configuration. Change the domain here once you buy it —
// everything (canonical URLs, sitemap, RSS, OG tags) reads from this.

export const SITE = {
  /** Production URL. No trailing slash. */
  url: "https://dawnwalker.wiki",
  /** Brand / site name shown in header, titles, schema. */
  name: "Dawnwalker Guide",
  /** Short tagline used in meta + OG description fallback. */
  tagline:
    "Guides, walkthroughs, builds, and daily news for The Blood of Dawnwalker.",
  /** Default social share image (1200x630, generated by scripts/process-art.mjs). */
  defaultImage: "/og-default.jpg",
  /** Language. English-only site. */
  lang: "en",
  locale: "en_US",
} as const;

// The game this site covers. Drives VideoGame schema and on-page facts.
export const GAME = {
  title: "The Blood of Dawnwalker",
  developer: "Rebel Wolves",
  publisher: "Bandai Namco Entertainment",
  releaseDate: "2026-09-03",
  genre: ["Action role-playing game", "Dark fantasy", "Narrative sandbox RPG"],
  platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
  officialSite: "https://dawnwalkergame.com",
} as const;

// Author identity for E-E-A-T. Add real bios on /about.
export const AUTHORS = {
  editorial: {
    name: "Dawnwalker Guide Team",
    url: "/about/",
  },
} as const;

// Analytics. Google Analytics 4 measurement ID (starts with "G-").
// Leave empty to disable; the gtag snippet only renders when set.
export const ANALYTICS = {
  gaId: "G-HMMM1Q8P7Q",
} as const;

// Monetization. Fill these in AFTER AdSense approval, then redeploy.
export const ADSENSE = {
  /** e.g. "ca-pub-1234567890123456". Leave empty until approved. */
  publisherId: "",
  /** Toggle to true once approved to render real ad units + load the script. */
  enabled: false,
} as const;

// Main navigation. Add items as sections grow.
export const NAV = [
  { label: "Home", href: "/" },
  { label: "Guides", href: "/guides/" },
  { label: "News", href: "/news/" },
  { label: "About", href: "/about/" },
] as const;
